### ISSUE TITLE
Increase the output frequency of pixhawk using mavros/Unable to connect to mavlink

### ISSUE THREAD

**Issue by utkarsh447** [mavlink/mavlink#1035]
### 1. I am trying to access pixhawk using GPIO via mavlink, but i cannot connect,
I get following error:
```
pi@pi:~$ mavproxy.py --master=/dev/ttyS0 --baudrate 57600 --aircraft aa1
WARNING: You should uninstall ModemManager as it conflicts with APM and Pixhawk
Connect /dev/ttyS0 source_system=255
no script aa1/mavinit.scr
Log Directory: aa1/logs/2018-12-10/flight1
Telemetry log: aa1/logs/2018-12-10/flight1/flight.tlog
Waiting for heartbeat from /dev/ttyS0
 MAV> Exception in thread main_loop:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/bin/mavproxy.py", line 811, in main_loop
    master.wait_heartbeat(timeout=0.1)
TypeError: wait_heartbeat() got an unexpected keyword argument 'timeout'

```

My mavlink library versions are as follows:
```
Name: pymavlink
Version: 2.0.6
Summary: Python MAVLink code
Home-page: http://github.com/mavlink/mavlink
Author: UNKNOWN
Author-email: UNKNOWN
License: LGPLv3
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
Required-by: MAVProxy, dronekit, droneapi
```
```
Name: MAVProxy
Version: 1.7.7
Summary: MAVProxy MAVLink ground station
Home-page: https://github.com/ArduPilot/MAVProxy
Author: Andrew Tridgell
Author-email: andrew@tridgell.net
License: GPLv3
Location: /usr/local/lib/python2.7/dist-packages
Requires: pymavlink, pyserial
Required-by: droneapi
```

Whereas when i try to connect via mavros using command:
`roslaunch mavros px4.launch fcu_url:=/dev/ttyS0:57600 tgt_system:=1`
I get the heartbeat with following log:
```
SUMMARY
========

CLEAR PARAMETERS
 * /mavros/

*** TOPIC LISTS ***

NODES
  /
    mavros (mavros/mavros_node)

auto-starting new master
process[master]: started with pid [25229]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7da38bfe-fc54-11e8-ae5c-b827ebb6c53f
WARNING: Package name "drone_FSM_flexbe_states" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "drone_FSM_flexbe_behaviors" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[rosout-1]: started with pid [25242]
started core service [/rosout]
process[mavros-2]: started with pid [25260]
[ INFO] [1544430049.697528061]: FCU URL: /dev/ttyS0:57600
[ INFO] [1544430049.708538453]: serial0: device: /dev/ttyS0 @ 57600 bps
[ INFO] [1544430049.709416982]: GCS bridge disabled
[ INFO] [1544430049.776808456]: Plugin 3dr_radio loaded
[ INFO] [1544430049.787194809]: Plugin 3dr_radio initialized
[ INFO] [1544430049.788016878]: Plugin actuator_control loaded
[ INFO] [1544430049.809127620]: Plugin actuator_control initialized
[ INFO] [1544430049.827694446]: Plugin adsb loaded
[ INFO] [1544430049.848801908]: Plugin adsb initialized
[ INFO] [1544430049.849809609]: Plugin altitude loaded
[ INFO] [1544430049.856779976]: Plugin altitude initialized
[ INFO] [1544430049.857700434]: Plugin cam_imu_sync loaded
[ INFO] [1544430049.862115633]: Plugin cam_imu_sync initialized
[ INFO] [1544430049.863042810]: Plugin command loaded
[ INFO] [1544430049.895048366]: Plugin command initialized
[ INFO] [1544430049.895940542]: Plugin debug_value loaded
[ INFO] [1544430049.930058277]: Plugin debug_value initialized
[ INFO] [1544430049.930237660]: Plugin distance_sensor blacklisted
[ INFO] [1544430049.931037019]: Plugin fake_gps loaded
[ INFO] [1544430050.029163940]: Plugin fake_gps initialized
[ INFO] [1544430050.030102472]: Plugin ftp loaded
[ INFO] [1544430050.079408704]: Plugin ftp initialized
[ INFO] [1544430050.080085766]: Plugin global_position loaded
[ INFO] [1544430050.200508379]: Plugin global_position initialized
[ INFO] [1544430050.201352011]: Plugin gps_rtk loaded
[ INFO] [1544430050.220766688]: Plugin gps_rtk initialized
[ INFO] [1544430050.221689021]: Plugin hil loaded
[ INFO] [1544430050.315938372]: Plugin hil initialized
[ INFO] [1544430050.316884977]: Plugin home_position loaded
[ INFO] [1544430050.343107669]: Plugin home_position initialized
[ INFO] [1544430050.344033804]: Plugin imu loaded
[ INFO] [1544430050.396765555]: Plugin imu initialized
[ INFO] [1544430050.397658460]: Plugin local_position loaded
[ INFO] [1544430050.437993819]: Plugin local_position initialized
[ INFO] [1544430050.438852920]: Plugin log_transfer loaded
[ INFO] [1544430050.458400260]: Plugin log_transfer initialized
[ INFO] [1544430050.459372022]: Plugin manual_control loaded
[ INFO] [1544430050.480417397]: Plugin manual_control initialized
[ INFO] [1544430050.481209985]: Plugin mocap_pose_estimate loaded
[ INFO] [1544430050.510639228]: Plugin mocap_pose_estimate initialized
[ INFO] [1544430050.511482130]: Plugin obstacle_distance loaded
[ INFO] [1544430050.530417567]: Plugin obstacle_distance initialized
[ INFO] [1544430050.531212082]: Plugin odom loaded
[ INFO] [1544430050.560403241]: Plugin odom initialized
[ INFO] [1544430050.561350679]: Plugin param loaded
[ INFO] [1544430050.577032480]: Plugin param initialized
[ INFO] [1544430050.577895748]: Plugin px4flow loaded
[ INFO] [1544430050.629643652]: Plugin px4flow initialized
[ INFO] [1544430050.630012523]: Plugin rangefinder blacklisted
[ INFO] [1544430050.630715107]: Plugin rc_io loaded
[ INFO] [1544430050.656673620]: Plugin rc_io initialized
[ INFO] [1544430050.657113901]: Plugin safety_area blacklisted
[ INFO] [1544430050.657858517]: Plugin setpoint_accel loaded
[ INFO] [1544430050.680833511]: Plugin setpoint_accel initialized
[ INFO] [1544430050.681828920]: Plugin setpoint_attitude loaded
[ INFO] [1544430050.752304127]: Plugin setpoint_attitude initialized
[ INFO] [1544430050.753231877]: Plugin setpoint_position loaded
[ INFO] [1544430050.850225258]: Plugin setpoint_position initialized
[ INFO] [1544430050.851141758]: Plugin setpoint_raw loaded
[ INFO] [1544430050.914007194]: Plugin setpoint_raw initialized
[ INFO] [1544430050.914866348]: Plugin setpoint_velocity loaded
[ INFO] [1544430050.956511297]: Plugin setpoint_velocity initialized
[ INFO] [1544430050.957428161]: Plugin sys_status loaded
[ INFO] [1544430051.017418052]: Plugin sys_status initialized
[ INFO] [1544430051.018280591]: Plugin sys_time loaded
[ INFO] [1544430051.059754126]: TM: Timesync mode: MAVLINK
[ INFO] [1544430051.068327742]: Plugin sys_time initialized
[ INFO] [1544430051.069037774]: Plugin trajectory loaded
[ INFO] [1544430051.108690967]: Plugin trajectory initialized
[ INFO] [1544430051.109480586]: Plugin vfr_hud loaded
[ INFO] [1544430051.113566759]: Plugin vfr_hud initialized
[ INFO] [1544430051.113760205]: Plugin vibration blacklisted
[ INFO] [1544430051.114579357]: Plugin vision_pose_estimate loaded
[ INFO] [1544430051.173833277]: Plugin vision_pose_estimate initialized
[ INFO] [1544430051.174534402]: Plugin vision_speed_estimate loaded
[ INFO] [1544430051.202687025]: Plugin vision_speed_estimate initialized
[ INFO] [1544430051.203756344]: Plugin waypoint loaded
[ INFO] [1544430051.234266729]: Plugin waypoint initialized
[ INFO] [1544430051.235080099]: Plugin wind_estimation loaded
[ INFO] [1544430051.239326228]: Plugin wind_estimation initialized
[ INFO] [1544430051.239590719]: Autostarting mavlink via USB on PX4
[ INFO] [1544430051.240037875]: Built-in SIMD instructions: None
[ INFO] [1544430051.240177308]: Built-in MAVLink package version: 2018.10.10
[ INFO] [1544430051.240366483]: Known MAVLink dialects: common ardupilotmega ASLUAV autoquad icarous matrixpilot paparazzi slugs standard uAvionix ualberta
[ INFO] [1544430051.240499250]: MAVROS started. MY ID 1.240, TARGET ID 1.1
[ WARN] [1544430051.681331770]: TM : RTT too high for timesync: 12.47 ms.
[ INFO] [1544430052.116239493]: CON: Got HEARTBEAT, connected. FCU: PX4 Autopilot
[ WARN] [1544430052.284526661]: TM : RTT too high for timesync: 15.52 ms.
[ WARN] [1544430052.883383805]: TM : RTT too high for timesync: 15.02 ms.
[ INFO] [1544430053.151922261]: RC_CHANNELS message detected!
[ INFO] [1544430053.171684194]: VER: 1.1: Capabilities         0x000000000000e4ef
[ INFO] [1544430053.172131974]: VER: 1.1: Flight software:     010801ff (0000000076FBB14B)
[ INFO] [1544430053.172903103]: VER: 1.1: Middleware software: 010801ff (0000000000000001)
[ INFO] [1544430053.173109102]: VER: 1.1: OS software:         071600ff (0000000000000001)
[ INFO] [1544430053.173250098]: VER: 1.1: Board hardware:      00000011
[ INFO] [1544430053.173998777]: VER: 1.1: VID/PID:             26ac:0011
[ INFO] [1544430053.174229934]: VER: 1.1: UID:                 3037511535383537
```

Please suggest the possible issues where i am unable to connect via mavlink and how to solve them?

### 2. I am trying to increase the output frequency of pixhawk using mavros:
I want to increase the frequency of IMU data output.
I am following PX4 option of the answer mentioned in the link,
[increase-output-frequency-of-pixhawk-using-mavros](https://answers.ros.org/question/213390/increase-output-frequency-of-pixhawk-using-mavros/), 
I am using Sanddisk ultra 16 GB class 10 Micro SD card and doing the following steps:
1. Formatted the SD card and inserted that card in Pixhawk, 
2. Ran pixhawk, performed basic commands, closed pixhawk, and check the contents of SD card, I got logs in that. (I can conclude SD card is working).
3. I created /etc/extras.txt folder in root with this code snippet: 
```
#!nsh
#
# MAVLink start
#

mavlink start -d /dev/ttyS0 -b 57600
# Enable a number of interesting streams we want via USB
mavlink stream -d /dev/ttyS0 -s ATTITUDE -r 200
mavlink stream -d /dev/ttyS0 -s HIGHRES_IMU -r 200

# Exit shell to make it available to MAVLink
exit
```
Inserted sdcard back and ran the pixhawk. With this, i am unable to get heartbeat. 
Please suggest the proper way to increase the output frequency from pixhawk?

**Comment by amilcarlucas** [comment]
update the pymavlink version to 2.3.4, update the mavros version to latest. and retry

**Comment by amilcarlucas** [comment]
If we get no answer, I vote we close this one.

**Comment by hamishwillee** [comment]
The first is failing because it can't see heartbeats on that input serial port. It may be failing here due to some other misconfiguration - i.e. there is no output param.
The second problem is PX4 specific and should be raised on the PX4 discussion boards. 

I'm closing this now thanks @amilcarlucas - because it is a mavproxy and/or PX4 problem, not a MAVLink problem *at this point*. @utkarsh447 Feel free to repost on PX4 discussion boards.
