### ISSUE TITLE
pip install of pymavlink 2.0.9 fails

### ISSUE THREAD

**Issue by jgoppert** [mavlink/mavlink#650]
jgoppert@rigor:~/git$ pip install pymavlink
Collecting pymavlink
  Using cached pymavlink-2.0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HMLjr0/pymavlink/setup.py", line 18, in <module>
        from generator import mavgen, mavparse
      File "/tmp/pip-build-HMLjr0/pymavlink/generator/mavgen.py", line 12, in <module>
        from future import standard_library
    ImportError: No module named future

**Comment by cclauss** [comment]
See https://github.com/ArduPilot/pymavlink/issues/25
